version: '2'
services:
  plantycomparepurchasingpower-mongodb:
    image: mongo:4.0.9
    ports:
      - '27037:27017'
    command: mongos --configdb plantycomparepurchasingpower-mongodb-config
  plantycomparepurchasingpower-mongodb-node:
    build:
      context: .
      dockerfile: mongodb/MongoDB.Dockerfile
    command: mongod --replSet rs1 --noprealloc --smallfiles
  plantycomparepurchasingpower-mongodb-config:
    image: mongo:4.0.9
    container_name: plantycomparepurchasingpower-mongodb-config
    command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
