version: '2'
services:
  plantycomparepurchasingpowerservice-mongodb:
    image: mongo:4.0.9
    ports:
      - '27037:27017'
    # volumes:
    #     - ~/volumes/jhipster/PlantyComparePurchasingPowerService/mongodb/:/data/db/
