version: '2'
services:
  plantycomparepurchasingpower-mongodb:
    image: mongo:4.0.9
    ports:
      - '27037:27017'
    # volumes:
    #     - ~/volumes/jhipster/PlantyComparePurchasingPower/mongodb/:/data/db/
